data_source: data
defaults:
  -
    scope:
      path: "data/days/*.md"
    values:
      permalink: /:basename.html
      layout: default
  -
    scope:
      path: "data/places/*/*.md"
    values:
      output: false
      
plugins:
  - jekyll-optional-front-matter
