data_dir: data

#theme: no-theme

defaults:
  -
    scope:
      path: "data/campaigns/*.md"
    values:
      permalink: /:basename.html
      layout: campaign

  -
    scope:
      path: "index.md"
    values:
      permalink: /index.html
      layout: index
      
plugins:
  - jekyll-optional-front-matter
