data_dir: data

#theme: no-theme

defaults:
  - scope:
      path: "assets/css"

  - scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "data/campaigns/*.md"
    values:
      permalink: /:basename.html
      layout: campaign

  -
    scope:
      path: "data/index.md"
    values:
      permalink: /index.html
      layout: index
      
plugins:
  - jekyll-optional-front-matter
