data_dir: assets

defaults:
  - scope:
      path: "assets/css"
  -
    scope:
      path: "data/campaigns/*/*.md"
    values:
      permalink: /:basename/
      layout: index

  -
    scope:
      path: "data/index/index.md"
    values:
      permalink: /index.html
      layout: index
      
plugins:
  - jekyll-optional-front-matter
