data_dir: data

defaults:
#
#  - scope:
#      path: "assets/img"
#    values:
#      image: true
#
  - scope:
      path: "assets/css"
  -
    scope:
      path: "data/campaigns/*/*.md"
    values:
      permalink: /:basename.html
      layout: campaign

  -
    scope:
      path: "data/index/index.md"
    values:
      permalink: /index.html
      layout: index
      
plugins:
  - jekyll-optional-front-matter
